baseURL = "https://example.net.eu.org/"
title = "Example Domain"
#enableRobotsTXT = true
#enableEmoji = true
theme = "hugo-theme-jane"

hasCJKLanguage = true     # has chinese/japanese/korean ?
paginate = 3              # Number of articles displayed on the homepage
rssLimit = 20             # Limit Entry Count to Rss file
disqusShortname = ""      # disqus_shortname
googleAnalytics = ""      # UA-XXXXXXXX-X
copyright = """
Presented by <a class="hexo-link" href="https://balloon.im/">BALLOON a.k.a. Fu-sen.</a> 🎈😍
"""                       # default: author.name ↓

disableKinds = ["RSS","sitemap","taxonomy","taxonomyTerm"]

# language support # en / zh-cn / other... translations present in i18n/
defaultContentLanguage = "en"           # Default language to use
languageCode = "en"

[author]                  # essential
  name = "BALLOON a.k.a. Fu-sen."

[sitemap]                 # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

#[[menu.main]]             # config your menu
#  name = "This is Home"
#  weight = 10
#  identifier = "home"
#  url = "/"
#[[menu.main]]
#  name = "Archives"
#  weight = 20
#  identifier = "archives"
#  url = "/post/"
#[[menu.main]]
#  name = "Tags"
#  weight = 30
#  identifier = "tags"
#  url = "/tags/"
#[[menu.main]]
#  name = "Categories"
#  weight = 40
#  identifier = "categories"
#  url = "/categories/"
#[[menu.main]]
#  name = "external-link"
#  weight = 50
#  url = "https://gohugo.io"


[params]
  since = "2020"            # Site creation time
  homeFullContent = false   # if false, show post summaries on home page. Othewise show full content.
  rssFullContent = true     # if false, Rss feed instead of the summary

  # site info (optional)
  logoTitle = "Example Domain"        # default: the title value
  #keywords = ["Hugo", "theme","jane"]
  description = "This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission."

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = false
  #photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  # Link custom CSS and JS assets
  #   (relative to /static/css and /static/js respectively)
  customCSS = ['custom.css']            # if ['custom.css'], load '/static/css/custom.css' file
  customJS = []             # if ['custom.js'], load '/static/js/custom.js' file

#  [params.social]
#    a-email = "mailto:your@email.com"
#    b-stack-overflow = "http://localhost:1313"
#    c-twitter = "http://localhost:1313"
#    d-facebook = "http://localhost:1313"
#    e-linkedin = "http://localhost:1313"
#    f-google = "http://localhost:1313"
#    g-github = "http://localhost:1313"
#    h-weibo = "http://localhost:1313"
#    i-zhihu = "http://localhost:1313"
#    j-douban = "http://localhost:1313"
#    k-pocket = "http://localhost:1313"
#    l-tumblr = "http://localhost:1313"
#    m-instagram = "http://localhost:1313"
#    n-gitlab = "http://localhost:1313"
#    o-goodreads = "http://localhost:1313"
#    p-coding = "http://localhost:1313"
#    q-bilibili = "http://localhost:1313"
#    r-codeforces = "http://localhost:1313"
#    s-mastodon = "http://localhost:1313"
